# -*- mode: toml -*-
# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
"$schema" = "https://pixi.sh/v0.59.0/schema/manifest/schema.json"

[workspace]
name = "momentum-feedstock"
version = "3.54.1"  # conda-smithy version used to generate this file
description = "Pixi configuration for conda-forge/momentum-feedstock"
authors = ["@conda-forge/momentum"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]
requires-pixi = ">=0.59.0"

[dependencies]
conda-build = ">=24.1"
conda-forge-ci-setup = "4.*"
python = "3.12.*"

[tasks.inspect-all]
cmd = "inspect_artifacts --all-packages"
description = "List contents of all packages found in conda-build build directory."
[tasks.build]
cmd = "conda-build build recipe"
description = "Build momentum-feedstock directly (without setup scripts), no particular variant specified"
[tasks.debug]
cmd = "conda-build debug recipe"
description = "Debug momentum-feedstock directly (without setup scripts), no particular variant specified"
[tasks."build-linux_64_cuda_compiler_version12.6pytorch2.7"]
cmd = "conda-build build recipe -m .ci_support/linux_64_cuda_compiler_version12.6pytorch2.7.yaml --suppress-variables --clobber-file .ci_support/clobber_linux_64_cuda_compiler_version12.6pytorch2.7.yaml"
description = "Build momentum-feedstock with variant linux_64_cuda_compiler_version12.6pytorch2.7 directly (without setup scripts)"
[tasks."debug-linux_64_cuda_compiler_version12.6pytorch2.7"]
cmd = "conda-build debug recipe -m .ci_support/linux_64_cuda_compiler_version12.6pytorch2.7.yaml"
description = "Debug momentum-feedstock with variant linux_64_cuda_compiler_version12.6pytorch2.7 directly (without setup scripts)"
[tasks."inspect-linux_64_cuda_compiler_version12.6pytorch2.7"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_cuda_compiler_version12.6pytorch2.7.yaml"
description = "List contents of momentum-feedstock packages built for variant linux_64_cuda_compiler_version12.6pytorch2.7"
[tasks."build-linux_64_cuda_compiler_version12.6pytorch2.9"]
cmd = "conda-build build recipe -m .ci_support/linux_64_cuda_compiler_version12.6pytorch2.9.yaml --suppress-variables --clobber-file .ci_support/clobber_linux_64_cuda_compiler_version12.6pytorch2.9.yaml"
description = "Build momentum-feedstock with variant linux_64_cuda_compiler_version12.6pytorch2.9 directly (without setup scripts)"
[tasks."debug-linux_64_cuda_compiler_version12.6pytorch2.9"]
cmd = "conda-build debug recipe -m .ci_support/linux_64_cuda_compiler_version12.6pytorch2.9.yaml"
description = "Debug momentum-feedstock with variant linux_64_cuda_compiler_version12.6pytorch2.9 directly (without setup scripts)"
[tasks."inspect-linux_64_cuda_compiler_version12.6pytorch2.9"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_cuda_compiler_version12.6pytorch2.9.yaml"
description = "List contents of momentum-feedstock packages built for variant linux_64_cuda_compiler_version12.6pytorch2.9"
[tasks."build-linux_64_cuda_compiler_version12.9pytorch2.7"]
cmd = "conda-build build recipe -m .ci_support/linux_64_cuda_compiler_version12.9pytorch2.7.yaml --suppress-variables --clobber-file .ci_support/clobber_linux_64_cuda_compiler_version12.9pytorch2.7.yaml"
description = "Build momentum-feedstock with variant linux_64_cuda_compiler_version12.9pytorch2.7 directly (without setup scripts)"
[tasks."debug-linux_64_cuda_compiler_version12.9pytorch2.7"]
cmd = "conda-build debug recipe -m .ci_support/linux_64_cuda_compiler_version12.9pytorch2.7.yaml"
description = "Debug momentum-feedstock with variant linux_64_cuda_compiler_version12.9pytorch2.7 directly (without setup scripts)"
[tasks."inspect-linux_64_cuda_compiler_version12.9pytorch2.7"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_cuda_compiler_version12.9pytorch2.7.yaml"
description = "List contents of momentum-feedstock packages built for variant linux_64_cuda_compiler_version12.9pytorch2.7"
[tasks."build-linux_64_cuda_compiler_version12.9pytorch2.9"]
cmd = "conda-build build recipe -m .ci_support/linux_64_cuda_compiler_version12.9pytorch2.9.yaml --suppress-variables --clobber-file .ci_support/clobber_linux_64_cuda_compiler_version12.9pytorch2.9.yaml"
description = "Build momentum-feedstock with variant linux_64_cuda_compiler_version12.9pytorch2.9 directly (without setup scripts)"
[tasks."debug-linux_64_cuda_compiler_version12.9pytorch2.9"]
cmd = "conda-build debug recipe -m .ci_support/linux_64_cuda_compiler_version12.9pytorch2.9.yaml"
description = "Debug momentum-feedstock with variant linux_64_cuda_compiler_version12.9pytorch2.9 directly (without setup scripts)"
[tasks."inspect-linux_64_cuda_compiler_version12.9pytorch2.9"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_cuda_compiler_version12.9pytorch2.9.yaml"
description = "List contents of momentum-feedstock packages built for variant linux_64_cuda_compiler_version12.9pytorch2.9"
[tasks."build-linux_64_cuda_compiler_versionNonepytorch2.7"]
cmd = "conda-build build recipe -m .ci_support/linux_64_cuda_compiler_versionNonepytorch2.7.yaml --suppress-variables --clobber-file .ci_support/clobber_linux_64_cuda_compiler_versionNonepytorch2.7.yaml"
description = "Build momentum-feedstock with variant linux_64_cuda_compiler_versionNonepytorch2.7 directly (without setup scripts)"
[tasks."debug-linux_64_cuda_compiler_versionNonepytorch2.7"]
cmd = "conda-build debug recipe -m .ci_support/linux_64_cuda_compiler_versionNonepytorch2.7.yaml"
description = "Debug momentum-feedstock with variant linux_64_cuda_compiler_versionNonepytorch2.7 directly (without setup scripts)"
[tasks."inspect-linux_64_cuda_compiler_versionNonepytorch2.7"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_cuda_compiler_versionNonepytorch2.7.yaml"
description = "List contents of momentum-feedstock packages built for variant linux_64_cuda_compiler_versionNonepytorch2.7"
[tasks."build-linux_64_cuda_compiler_versionNonepytorch2.9"]
cmd = "conda-build build recipe -m .ci_support/linux_64_cuda_compiler_versionNonepytorch2.9.yaml --suppress-variables --clobber-file .ci_support/clobber_linux_64_cuda_compiler_versionNonepytorch2.9.yaml"
description = "Build momentum-feedstock with variant linux_64_cuda_compiler_versionNonepytorch2.9 directly (without setup scripts)"
[tasks."debug-linux_64_cuda_compiler_versionNonepytorch2.9"]
cmd = "conda-build debug recipe -m .ci_support/linux_64_cuda_compiler_versionNonepytorch2.9.yaml"
description = "Debug momentum-feedstock with variant linux_64_cuda_compiler_versionNonepytorch2.9 directly (without setup scripts)"
[tasks."inspect-linux_64_cuda_compiler_versionNonepytorch2.9"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_cuda_compiler_versionNonepytorch2.9.yaml"
description = "List contents of momentum-feedstock packages built for variant linux_64_cuda_compiler_versionNonepytorch2.9"
[tasks."build-osx_64_"]
cmd = "conda-build build recipe -m .ci_support/osx_64_.yaml --suppress-variables --clobber-file .ci_support/clobber_osx_64_.yaml"
description = "Build momentum-feedstock with variant osx_64_ directly (without setup scripts)"
[tasks."debug-osx_64_"]
cmd = "conda-build debug recipe -m .ci_support/osx_64_.yaml"
description = "Debug momentum-feedstock with variant osx_64_ directly (without setup scripts)"
[tasks."inspect-osx_64_"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_.yaml"
description = "List contents of momentum-feedstock packages built for variant osx_64_"
[tasks."build-osx_arm64_"]
cmd = "conda-build build recipe -m .ci_support/osx_arm64_.yaml --suppress-variables --clobber-file .ci_support/clobber_osx_arm64_.yaml"
description = "Build momentum-feedstock with variant osx_arm64_ directly (without setup scripts)"
[tasks."debug-osx_arm64_"]
cmd = "conda-build debug recipe -m .ci_support/osx_arm64_.yaml"
description = "Debug momentum-feedstock with variant osx_arm64_ directly (without setup scripts)"
[tasks."inspect-osx_arm64_"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_.yaml"
description = "List contents of momentum-feedstock packages built for variant osx_arm64_"
[tasks."build-win_64_cuda_compiler_version12.9"]
cmd = "conda-build build recipe -m .ci_support/win_64_cuda_compiler_version12.9.yaml --suppress-variables --clobber-file .ci_support/clobber_win_64_cuda_compiler_version12.9.yaml"
description = "Build momentum-feedstock with variant win_64_cuda_compiler_version12.9 directly (without setup scripts)"
[tasks."debug-win_64_cuda_compiler_version12.9"]
cmd = "conda-build debug recipe -m .ci_support/win_64_cuda_compiler_version12.9.yaml"
description = "Debug momentum-feedstock with variant win_64_cuda_compiler_version12.9 directly (without setup scripts)"
[tasks."inspect-win_64_cuda_compiler_version12.9"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/win_64_cuda_compiler_version12.9.yaml"
description = "List contents of momentum-feedstock packages built for variant win_64_cuda_compiler_version12.9"
[tasks."build-win_64_cuda_compiler_versionNone"]
cmd = "conda-build build recipe -m .ci_support/win_64_cuda_compiler_versionNone.yaml --suppress-variables --clobber-file .ci_support/clobber_win_64_cuda_compiler_versionNone.yaml"
description = "Build momentum-feedstock with variant win_64_cuda_compiler_versionNone directly (without setup scripts)"
[tasks."debug-win_64_cuda_compiler_versionNone"]
cmd = "conda-build debug recipe -m .ci_support/win_64_cuda_compiler_versionNone.yaml"
description = "Debug momentum-feedstock with variant win_64_cuda_compiler_versionNone directly (without setup scripts)"
[tasks."inspect-win_64_cuda_compiler_versionNone"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/win_64_cuda_compiler_versionNone.yaml"
description = "List contents of momentum-feedstock packages built for variant win_64_cuda_compiler_versionNone"

[feature.smithy.dependencies]
conda-smithy = "*"
[feature.smithy.tasks.build-locally]
cmd = "python ./build-locally.py"
description = "Build packages locally using the same setup scripts used in conda-forge's CI"
[feature.smithy.tasks.smithy]
cmd = "conda-smithy"
description = "Run conda-smithy. Pass necessary arguments."
[feature.smithy.tasks.rerender]
cmd = "conda-smithy rerender"
description = "Rerender the feedstock."
[feature.smithy.tasks.lint]
cmd = "conda-smithy lint --conda-forge recipe"
description = "Lint the feedstock recipe"

[environments]
smithy = ["smithy"]

# This is a copy of default, to be enabled by build_steps.sh during Docker builds
# __PLATFORM_SPECIFIC_ENV__ = []
